### ISSUE TITLE
License

### ISSUE THREAD

**Issue by josht000** [jahongir7174/YOLOv8-pose#1]
All code needs a license of some sort like [MIT](https://opensource.org/license/mit/), [Apache 2.0,](https://www.apache.org/licenses/LICENSE-2.0.txt) the [Unlicense license](https://github.com/realworldocaml/examples/blob/master/UNLICENSE) etc. Could you please chose a permissive O/S license for your project?

Thanks!

**Comment by jahongir7174** [comment]
@josht000 
I have added a license like the original [YOLOv8](https://github.com/ultralytics/ultralytics) to avoid further conflict.
