### ISSUE TITLE
Some problems in Dataset structure

### ISSUE THREAD

**Issue by Just-zy** [jahongir7174/YOLOv8-pose#2]
Thank you for your work, 
can you give more details about dataset structure, it looks different from the code which has **train2017.txt and val2017.txt.** I found possible txt files and put them under COCOPose, at the same level as images and labels, the content of train2017.txt is **./images/train2017/000000391895.jpg ......** (one per line). The content of val2017.txt is **./images/val2017/000000182611.jpg ......** (one per line). 
In addition, there was an error. I modified line 583 of utils.py based on the yolov8 source code, changing **traget_bboxes, target_scores, fg_mask,traget_gt_idx = assigned_targets** to **_, traget_bboxes, target_scores, fg_mask,traget_gt_idx = assigned_targets**. I successfully ran the code, but **BoxAP And PoseAP is still 0** after dozens of rounds of training, and it is also 0 after running the test code using the weights you provided. I would like to know whether it is a problem with the dataset or something else, and I look forward to your reply.

**Comment by Just-zy** [comment]
> Thank you for your work,
> can you give more details about dataset structure, it looks different from the code which has **train2017.txt and val2017.txt.** I found possible txt files and put them under COCOPose, at the same level as images and labels, the content of train2017.txt is **./images/train2017/000000391895.jpg ......** (one per line). The content of val2017.txt is **./images/val2017/000000182611.jpg ......** (one per line).
> In addition, there was an error. I modified line 583 of utils.py based on the yolov8 source code, changing **traget_bboxes, target_scores, fg_mask,traget_gt_idx = assigned_targets** to **_, traget_bboxes, target_scores, fg_mask,traget_gt_idx = assigned_targets**. I successfully ran the code, but **BoxAP And PoseAP is still 0** after dozens of rounds of training, and it is also 0 after running the test code using the weights you provided. I would like to know whether it is a problem with the dataset or something else, and I look forward to your reply.

I have sovled the question.

**Comment by mycodeDev786** [comment]
@Just-zy, can you please update how you can correct this? I am facing the same issue and am unable to solve it. It will be very kind to me

**Comment by mycodeDev786** [comment]
@jahongir7174 can you please guide for the above error
